### PR TITLE
added method saveBlob

### PR DESCRIPTION
**Pull request by oherych**
I added method saveBlob for string data. Please test on S3 server

### CODE REVIEW

**Comment by tonydspaniard** [comment]
@DieselDraft I will update asap. thank you.

**Comment by slavcodev** [comment]
@tonydspaniard any chance to get this closed? :D I'm spammed with notifications about stale PR where I'm mentioned every day, Thank you.

**Comment by oherych** [comment]
@slavcodev fill free to close it. I'm not working with more then PHP 6 years :)

**Comment by slavcodev** [comment]
@oherych I don't have permissions to close it.

**Comment by oherych** [comment]
done

**Pull request closed without merging**
